### ISSUE TITLE
Improve error message for when dates are missing.

### ISSUE THREAD

**Issue by hectorcustodiozup** [ZupIT/header-license-checker#6]
Hi,

We received and external contribution on our project and the user could not solve it by himself due to the lack of detailing on the message, see below:

Today when we set a copyright it seems that your code looks for initial and current Years in the header, but if we add only the current year the error message is as follows:

![image](https://user-images.githubusercontent.com/50678762/144850083-d9518104-c6a3-479e-8dd8-13bfa82febd2.png)

It does not state crearly what you mean by that, I think a better approch would be. Expected ```Copyright startYear, currentYear``` missing!

**Comment by thallesfreitaszup** [comment]
hi @hectorcustodiozup, thanks for the suggestion. I will work on this

**Comment by thallesfreitaszup** [comment]
hi @hectorcustodiozup Check the release https://github.com/ZupIT/header-license-checker/releases/tag/0.0.3 for the fix, if don't solve please reopen. Thanks!
